options:
  app-name:
    type: string
    default: "x1"
    description: "Description of xclarity application"
  skin:
    type: string
    default: vector
    description: skin for the Wiki
  logo:
    type: string
    default:
    description: URL to fetch logo from
  admins:
    type: string
    default:
    description: Admin users to create, user:pass
  debug:
    type: boolean
    default: false
    description: turn on debugging features of mediawiki
