options:
  app-name:
    type: string
    default: "Switch"
    description: "This is a switch"
  size:
    type: string
    default: "1U"
    description: "1U/2U"
  speed:
    type: string
    default: "1G"
    description: "1G/10G"
  cooling-orientation:
    type: string
    default: "Horizontal"
    description: "Horizontal/Vertical"
  port-config-json:
    type: string
    default: ""
    description: "Por config JSON"
  configuration-url:
    type: string
    default: "http://10.0.240.43/server/configuration/"
    description: "Server configuration file URL"
