options:
  string-option:
    type: string
    default: "Default Value"
    description: "A short description of the configuration option"
  boolean-option:
    type: boolean
    default: False
    description: "A short description of the configuration option"
  int-option:
    type: int
    default: 9001
    description: "A short description of the configuration option"


  django-port:
    default: 8000
    type: int
    description: "Port which Django application (gunicorn) should run on"
  django-debug:
    default: False
    type: boolean
    description: "Put Django in Debug mode"
  install-path:
    type: string
    default: "/home/ubuntu/source/"
    description: "the place to download files"
  source:
    type: string
    default: "git@github.com:zhougit86/django_demo.git"
    description: "A short description of the configuration option"


