options:
  app-name:
    type: string
    default: "Server"
    description: "This is a server"
  size:
    type: string
    default: "1U"
    description: "1U/2U"
  server-ip:
    type: string
    default: "192.168.0.100"
    description: "Assigned server IP address"
  front-disk-config-json:
    type: string
    default: ""
    description: "Front disk configuration JSON"
  back-disk-config-json:
    type: string
    default: ""
    description: "Back disk configuration JSON"
