options:
  app-name:
    type: string
    default: "ThinkAgile"
    description: "Solution name"
  solution-id:
    type: string
    default: ""
    description: "Solution ID"
  internal-name:
    type: string
    default: "ThinkAgile RTP"
    description: "Solution internal name"
  major-version:
    type: int
    default: 1
    description: "Major version"
